[tool.poetry]
name = "ml_training_suite"
version = "0.1.0"
description = ""
authors = ["Mark Zimmerman <mzimm003@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
onnx = "*"
onnxruntime = "*"
scikit-learn = "*"
pandas = "*"
numpy = "*"
torch = "*"
ray = {version="*", extras=["tune"]}
skl2onnx = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"